# Generated by Django 5.1.6 on 2025-03-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0002_category_menuitem_cart_order_orderitem_delete_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
